global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: onboard-backend-go
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend-go:8081
