// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AceAnalysisPrimaryCategory.
const (
	AceAnalysisPrimaryCategoryABILITY     AceAnalysisPrimaryCategory = "ABILITY"
	AceAnalysisPrimaryCategoryCULTURE     AceAnalysisPrimaryCategory = "CULTURE"
	AceAnalysisPrimaryCategoryEXPECTATION AceAnalysisPrimaryCategory = "EXPECTATION"
)

// Defines values for AgentTaskResponseStatus.
const (
	AgentTaskResponseStatusCOMPLETED AgentTaskResponseStatus = "COMPLETED"
	AgentTaskResponseStatusFAILED    AgentTaskResponseStatus = "FAILED"
)

// Defines values for AgentToolCallStatus.
const (
	AgentToolCallStatusCOMPLETED AgentToolCallStatus = "COMPLETED"
	AgentToolCallStatusFAILED    AgentToolCallStatus = "FAILED"
)

// Defines values for GroundednessCaseEvaluationCaseRequestExpectedStatus.
const (
	GroundednessCaseEvaluationCaseRequestExpectedStatusGROUNDED        GroundednessCaseEvaluationCaseRequestExpectedStatus = "GROUNDED"
	GroundednessCaseEvaluationCaseRequestExpectedStatusJUDGEERROR      GroundednessCaseEvaluationCaseRequestExpectedStatus = "JUDGE_ERROR"
	GroundednessCaseEvaluationCaseRequestExpectedStatusLOWGROUNDEDNESS GroundednessCaseEvaluationCaseRequestExpectedStatus = "LOW_GROUNDEDNESS"
	GroundednessCaseEvaluationCaseRequestExpectedStatusNOEVIDENCE      GroundednessCaseEvaluationCaseRequestExpectedStatus = "NO_EVIDENCE"
	GroundednessCaseEvaluationCaseRequestExpectedStatusPARSEFAILED     GroundednessCaseEvaluationCaseRequestExpectedStatus = "PARSE_FAILED"
)

// Defines values for GroundednessCaseEvaluationCaseResultActualStatus.
const (
	GroundednessCaseEvaluationCaseResultActualStatusGROUNDED        GroundednessCaseEvaluationCaseResultActualStatus = "GROUNDED"
	GroundednessCaseEvaluationCaseResultActualStatusJUDGEERROR      GroundednessCaseEvaluationCaseResultActualStatus = "JUDGE_ERROR"
	GroundednessCaseEvaluationCaseResultActualStatusLOWGROUNDEDNESS GroundednessCaseEvaluationCaseResultActualStatus = "LOW_GROUNDEDNESS"
	GroundednessCaseEvaluationCaseResultActualStatusNOEVIDENCE      GroundednessCaseEvaluationCaseResultActualStatus = "NO_EVIDENCE"
	GroundednessCaseEvaluationCaseResultActualStatusPARSEFAILED     GroundednessCaseEvaluationCaseResultActualStatus = "PARSE_FAILED"
)

// Defines values for GroundednessCaseEvaluationCaseResultExpectedStatus.
const (
	GroundednessCaseEvaluationCaseResultExpectedStatusGROUNDED        GroundednessCaseEvaluationCaseResultExpectedStatus = "GROUNDED"
	GroundednessCaseEvaluationCaseResultExpectedStatusJUDGEERROR      GroundednessCaseEvaluationCaseResultExpectedStatus = "JUDGE_ERROR"
	GroundednessCaseEvaluationCaseResultExpectedStatusLOWGROUNDEDNESS GroundednessCaseEvaluationCaseResultExpectedStatus = "LOW_GROUNDEDNESS"
	GroundednessCaseEvaluationCaseResultExpectedStatusNOEVIDENCE      GroundednessCaseEvaluationCaseResultExpectedStatus = "NO_EVIDENCE"
	GroundednessCaseEvaluationCaseResultExpectedStatusPARSEFAILED     GroundednessCaseEvaluationCaseResultExpectedStatus = "PARSE_FAILED"
)

// Defines values for GroundednessCaseEvaluationEvidenceAceCategory.
const (
	GroundednessCaseEvaluationEvidenceAceCategoryABILITY     GroundednessCaseEvaluationEvidenceAceCategory = "ABILITY"
	GroundednessCaseEvaluationEvidenceAceCategoryCULTURE     GroundednessCaseEvaluationEvidenceAceCategory = "CULTURE"
	GroundednessCaseEvaluationEvidenceAceCategoryEXPECTATION GroundednessCaseEvaluationEvidenceAceCategory = "EXPECTATION"
)

// Defines values for GroundednessEvaluationStatus.
const (
	GroundednessEvaluationStatusGROUNDED        GroundednessEvaluationStatus = "GROUNDED"
	GroundednessEvaluationStatusJUDGEERROR      GroundednessEvaluationStatus = "JUDGE_ERROR"
	GroundednessEvaluationStatusLOWGROUNDEDNESS GroundednessEvaluationStatus = "LOW_GROUNDEDNESS"
	GroundednessEvaluationStatusNOEVIDENCE      GroundednessEvaluationStatus = "NO_EVIDENCE"
	GroundednessEvaluationStatusPARSEFAILED     GroundednessEvaluationStatus = "PARSE_FAILED"
)

// Defines values for KnowledgeDocumentCreateRequestAccessScope.
const (
	KnowledgeDocumentCreateRequestAccessScopeADMINONLY KnowledgeDocumentCreateRequestAccessScope = "ADMIN_ONLY"
	KnowledgeDocumentCreateRequestAccessScopeSHARED    KnowledgeDocumentCreateRequestAccessScope = "SHARED"
)

// Defines values for KnowledgeDocumentCreateRequestAceCategory.
const (
	KnowledgeDocumentCreateRequestAceCategoryABILITY     KnowledgeDocumentCreateRequestAceCategory = "ABILITY"
	KnowledgeDocumentCreateRequestAceCategoryCULTURE     KnowledgeDocumentCreateRequestAceCategory = "CULTURE"
	KnowledgeDocumentCreateRequestAceCategoryEXPECTATION KnowledgeDocumentCreateRequestAceCategory = "EXPECTATION"
)

// Defines values for KnowledgeDocumentResponseAccessScope.
const (
	KnowledgeDocumentResponseAccessScopeADMINONLY KnowledgeDocumentResponseAccessScope = "ADMIN_ONLY"
	KnowledgeDocumentResponseAccessScopeSHARED    KnowledgeDocumentResponseAccessScope = "SHARED"
)

// Defines values for KnowledgeDocumentResponseAceCategory.
const (
	KnowledgeDocumentResponseAceCategoryABILITY     KnowledgeDocumentResponseAceCategory = "ABILITY"
	KnowledgeDocumentResponseAceCategoryCULTURE     KnowledgeDocumentResponseAceCategory = "CULTURE"
	KnowledgeDocumentResponseAceCategoryEXPECTATION KnowledgeDocumentResponseAceCategory = "EXPECTATION"
)

// Defines values for KnowledgeDocumentUpdateRequestAccessScope.
const (
	ADMINONLY KnowledgeDocumentUpdateRequestAccessScope = "ADMIN_ONLY"
	SHARED    KnowledgeDocumentUpdateRequestAccessScope = "SHARED"
)

// Defines values for KnowledgeDocumentUpdateRequestAceCategory.
const (
	KnowledgeDocumentUpdateRequestAceCategoryABILITY     KnowledgeDocumentUpdateRequestAceCategory = "ABILITY"
	KnowledgeDocumentUpdateRequestAceCategoryCULTURE     KnowledgeDocumentUpdateRequestAceCategory = "CULTURE"
	KnowledgeDocumentUpdateRequestAceCategoryEXPECTATION KnowledgeDocumentUpdateRequestAceCategory = "EXPECTATION"
)

// Defines values for RetrievedDocumentAceCategory.
const (
	RetrievedDocumentAceCategoryABILITY     RetrievedDocumentAceCategory = "ABILITY"
	RetrievedDocumentAceCategoryCULTURE     RetrievedDocumentAceCategory = "CULTURE"
	RetrievedDocumentAceCategoryEXPECTATION RetrievedDocumentAceCategory = "EXPECTATION"
)

// Defines values for GetKnowledgeReindexJobsParamsStatus.
const (
	COMPLETED GetKnowledgeReindexJobsParamsStatus = "COMPLETED"
	FAILED    GetKnowledgeReindexJobsParamsStatus = "FAILED"
	QUEUED    GetKnowledgeReindexJobsParamsStatus = "QUEUED"
	RUNNING   GetKnowledgeReindexJobsParamsStatus = "RUNNING"
)

// Defines values for GetKnowledgeReindexJobsParamsSortBy.
const (
	AcceptedAt  GetKnowledgeReindexJobsParamsSortBy = "acceptedAt"
	CompletedAt GetKnowledgeReindexJobsParamsSortBy = "completedAt"
)

// Defines values for GetKnowledgeReindexJobsParamsSortDirection.
const (
	Asc  GetKnowledgeReindexJobsParamsSortDirection = "asc"
	Desc GetKnowledgeReindexJobsParamsSortDirection = "desc"
)

// AceAnalysis defines model for AceAnalysis.
type AceAnalysis struct {
	PrimaryCategory AceAnalysisPrimaryCategory `json:"primaryCategory"`
	Reason          string                     `json:"reason"`
}

// AceAnalysisPrimaryCategory defines model for AceAnalysis.PrimaryCategory.
type AceAnalysisPrimaryCategory string

// AdviceRequest defines model for AdviceRequest.
type AdviceRequest struct {
	MemberContext MemberContext  `json:"memberContext"`
	Setting       *AdviceSetting `json:"setting,omitempty"`
}

// AdviceResponse defines model for AdviceResponse.
type AdviceResponse struct {
	AceAnalysis AceAnalysis `json:"aceAnalysis"`

	// Advice 生成されたアドバイス
	Advice                 string                 `json:"advice"`
	GroundednessEvaluation GroundednessEvaluation `json:"groundednessEvaluation"`
	RetrievedDocuments     []RetrievedDocument    `json:"retrievedDocuments"`
	Usage                  UsageInfo              `json:"usage"`
}

// AdviceSetting defines model for AdviceSetting.
type AdviceSetting struct {
	// Model 使用するLLMモデル名
	Model *string `json:"model,omitempty"`

	// Tone 回答のトーン
	Tone *string `json:"tone,omitempty"`
}

// AgentTaskRequest defines model for AgentTaskRequest.
type AgentTaskRequest struct {
	// Input Agent に依頼する自然文 task
	Input string `json:"input"`

	// MaxTurns Agents SDK runner の最大 turn 数。未指定時は backend 設定値を使う。
	MaxTurns *int `json:"maxTurns,omitempty"`
}

// AgentTaskResponse defines model for AgentTaskResponse.
type AgentTaskResponse struct {
	FailureReason *string                 `json:"failureReason,omitempty"`
	FinalAnswer   string                  `json:"finalAnswer"`
	Status        AgentTaskResponseStatus `json:"status"`
	TaskId        string                  `json:"taskId"`
	ToolCalls     []AgentToolCall         `json:"toolCalls"`
	TraceId       *string                 `json:"traceId,omitempty"`
}

// AgentTaskResponseStatus defines model for AgentTaskResponse.Status.
type AgentTaskResponseStatus string

// AgentToolCall defines model for AgentToolCall.
type AgentToolCall struct {
	ErrorMessage  *string             `json:"errorMessage,omitempty"`
	InputSummary  *string             `json:"inputSummary,omitempty"`
	LatencyMs     int64               `json:"latencyMs"`
	OutputSummary *string             `json:"outputSummary,omitempty"`
	Status        AgentToolCallStatus `json:"status"`
	ToolName      string              `json:"toolName"`
}

// AgentToolCallStatus defines model for AgentToolCall.Status.
type AgentToolCallStatus string

// AuditLogDetailResponse defines model for AuditLogDetailResponse.
type AuditLogDetailResponse struct {
	CompletionTokens       int                    `json:"completionTokens"`
	CostJpy                float64                `json:"costJpy"`
	CreatedAt              time.Time              `json:"createdAt"`
	GroundednessEvaluation GroundednessEvaluation `json:"groundednessEvaluation"`
	Id                     int64                  `json:"id"`
	LatencyMs              int64                  `json:"latencyMs"`
	Model                  string                 `json:"model"`
	Prompt                 string                 `json:"prompt"`
	PromptTokens           int                    `json:"promptTokens"`
	Response               string                 `json:"response"`
	TotalTokens            int                    `json:"totalTokens"`
}

// AuditLogListResponse defines model for AuditLogListResponse.
type AuditLogListResponse struct {
	Items      []AuditLogSummaryItem `json:"items"`
	Limit      int                   `json:"limit"`
	Offset     int                   `json:"offset"`
	TotalCount int64                 `json:"totalCount"`
}

// AuditLogSummaryItem defines model for AuditLogSummaryItem.
type AuditLogSummaryItem struct {
	CompletionTokens       int                    `json:"completionTokens"`
	CostJpy                float64                `json:"costJpy"`
	CreatedAt              time.Time              `json:"createdAt"`
	GroundednessEvaluation GroundednessEvaluation `json:"groundednessEvaluation"`
	Id                     int64                  `json:"id"`
	LatencyMs              int64                  `json:"latencyMs"`
	Model                  string                 `json:"model"`
	PromptTokens           int                    `json:"promptTokens"`
	TotalTokens            int                    `json:"totalTokens"`
}

// AuthTokenRequest defines model for AuthTokenRequest.
type AuthTokenRequest struct {
	// Password ログインパスワード
	Password string `json:"password"`

	// Username ログインユーザー名
	Username string `json:"username"`
}

// AuthTokenResponse defines model for AuthTokenResponse.
type AuthTokenResponse struct {
	// AccessToken API 呼び出しに利用する JWT
	AccessToken string    `json:"accessToken"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Roles       []string  `json:"roles"`
	TokenType   string    `json:"tokenType"`
	Username    string    `json:"username"`
}

// DashboardSummaryResponse defines model for DashboardSummaryResponse.
type DashboardSummaryResponse struct {
	AbilityKnowledgeDocuments     int64   `json:"abilityKnowledgeDocuments"`
	AverageCostJpy                float64 `json:"averageCostJpy"`
	AverageGroundednessScore      float64 `json:"averageGroundednessScore"`
	AverageLatencyMs              float64 `json:"averageLatencyMs"`
	CompletedReindexJobs          int64   `json:"completedReindexJobs"`
	CultureKnowledgeDocuments     int64   `json:"cultureKnowledgeDocuments"`
	ExpectationKnowledgeDocuments int64   `json:"expectationKnowledgeDocuments"`
	FailedReindexJobs             int64   `json:"failedReindexJobs"`
	GroundedResponses             int64   `json:"groundedResponses"`
	GroundednessFallbackResponses int64   `json:"groundednessFallbackResponses"`
	LowGroundednessResponses      int64   `json:"lowGroundednessResponses"`

	// OpenAiCircuitOpenTransitions circuit breaker が OPEN に遷移した回数
	OpenAiCircuitOpenTransitions float64 `json:"openAiCircuitOpenTransitions"`

	// OpenAiCircuitState 現在の OpenAI circuit breaker 状態
	OpenAiCircuitState string `json:"openAiCircuitState"`

	// OpenAiFailFastCount circuit breaker が OPEN/HALF_OPEN 制限で fail-fast した回数
	OpenAiFailFastCount float64 `json:"openAiFailFastCount"`

	// OpenAiRetryAttempts アプリ起動後に OpenAI 呼び出しで実施した retry 回数
	OpenAiRetryAttempts float64 `json:"openAiRetryAttempts"`

	// OpenAiTimeouts アプリ起動後に発生した OpenAI timeout 件数
	OpenAiTimeouts    float64 `json:"openAiTimeouts"`
	QueuedReindexJobs int64   `json:"queuedReindexJobs"`

	// ReindexSuccessRate completed / (completed + failed) を 0.0 から 1.0 で返す
	ReindexSuccessRate           float64 `json:"reindexSuccessRate"`
	RestrictedKnowledgeDocuments int64   `json:"restrictedKnowledgeDocuments"`
	RunningReindexJobs           int64   `json:"runningReindexJobs"`
	SharedKnowledgeDocuments     int64   `json:"sharedKnowledgeDocuments"`
	TotalAdviceRequests          int64   `json:"totalAdviceRequests"`
	TotalKnowledgeChunks         int64   `json:"totalKnowledgeChunks"`
	TotalKnowledgeDocuments      int64   `json:"totalKnowledgeDocuments"`
	TotalReindexJobs             int64   `json:"totalReindexJobs"`

	// VectorAcceptedRetrievals アプリ起動後に vector 検索結果が採用された回数
	VectorAcceptedRetrievals float64 `json:"vectorAcceptedRetrievals"`

	// VectorThresholdFallbacks similarity threshold により keyword fallback した回数
	VectorThresholdFallbacks float64 `json:"vectorThresholdFallbacks"`

	// VectorThresholdFilteredChunks similarity threshold により除外された chunk 数
	VectorThresholdFilteredChunks float64 `json:"vectorThresholdFilteredChunks"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]string `json:"details,omitempty"`
	Message *string   `json:"message,omitempty"`
	Status  *int      `json:"status,omitempty"`
}

// GroundednessCaseEvaluationCaseRequest defines model for GroundednessCaseEvaluationCaseRequest.
type GroundednessCaseEvaluationCaseRequest struct {
	Advice                  string                                              `json:"advice"`
	ExpectedFallbackApplied *bool                                               `json:"expectedFallbackApplied,omitempty"`
	ExpectedStatus          GroundednessCaseEvaluationCaseRequestExpectedStatus `json:"expectedStatus"`
	Label                   *string                                             `json:"label,omitempty"`
	RetrievedDocuments      []GroundednessCaseEvaluationEvidence                `json:"retrievedDocuments"`
	Situation               string                                              `json:"situation"`
	TargetGoal              string                                              `json:"targetGoal"`
}

// GroundednessCaseEvaluationCaseRequestExpectedStatus defines model for GroundednessCaseEvaluationCaseRequest.ExpectedStatus.
type GroundednessCaseEvaluationCaseRequestExpectedStatus string

// GroundednessCaseEvaluationCaseResult defines model for GroundednessCaseEvaluationCaseResult.
type GroundednessCaseEvaluationCaseResult struct {
	ActualStatus            GroundednessCaseEvaluationCaseResultActualStatus   `json:"actualStatus"`
	Advice                  string                                             `json:"advice"`
	ExpectedFallbackApplied bool                                               `json:"expectedFallbackApplied"`
	ExpectedStatus          GroundednessCaseEvaluationCaseResultExpectedStatus `json:"expectedStatus"`
	FallbackApplied         bool                                               `json:"fallbackApplied"`
	GroundednessScore       float64                                            `json:"groundednessScore"`
	Label                   *string                                            `json:"label,omitempty"`
	Matched                 bool                                               `json:"matched"`
	Reason                  string                                             `json:"reason"`
	Situation               string                                             `json:"situation"`
	TargetGoal              string                                             `json:"targetGoal"`
}

// GroundednessCaseEvaluationCaseResultActualStatus defines model for GroundednessCaseEvaluationCaseResult.ActualStatus.
type GroundednessCaseEvaluationCaseResultActualStatus string

// GroundednessCaseEvaluationCaseResultExpectedStatus defines model for GroundednessCaseEvaluationCaseResult.ExpectedStatus.
type GroundednessCaseEvaluationCaseResultExpectedStatus string

// GroundednessCaseEvaluationEvidence defines model for GroundednessCaseEvaluationEvidence.
type GroundednessCaseEvaluationEvidence struct {
	AceCategory GroundednessCaseEvaluationEvidenceAceCategory `json:"aceCategory"`
	Excerpt     string                                        `json:"excerpt"`
	Title       string                                        `json:"title"`
}

// GroundednessCaseEvaluationEvidenceAceCategory defines model for GroundednessCaseEvaluationEvidence.AceCategory.
type GroundednessCaseEvaluationEvidenceAceCategory string

// GroundednessCaseEvaluationRequest defines model for GroundednessCaseEvaluationRequest.
type GroundednessCaseEvaluationRequest struct {
	Cases []GroundednessCaseEvaluationCaseRequest `json:"cases"`
}

// GroundednessCaseEvaluationResponse defines model for GroundednessCaseEvaluationResponse.
type GroundednessCaseEvaluationResponse struct {
	Accuracy                 float64                                `json:"accuracy"`
	AverageGroundednessScore float64                                `json:"averageGroundednessScore"`
	CaseResults              []GroundednessCaseEvaluationCaseResult `json:"caseResults"`
	FallbackAppliedCases     int                                    `json:"fallbackAppliedCases"`
	GroundedCases            int                                    `json:"groundedCases"`
	JudgeErrorCases          int                                    `json:"judgeErrorCases"`
	LowGroundednessCases     int                                    `json:"lowGroundednessCases"`
	MatchedCases             int                                    `json:"matchedCases"`
	NoEvidenceCases          int                                    `json:"noEvidenceCases"`
	ParseFailedCases         int                                    `json:"parseFailedCases"`
	TotalCases               int                                    `json:"totalCases"`
}

// GroundednessEvaluation defines model for GroundednessEvaluation.
type GroundednessEvaluation struct {
	// FallbackApplied 低信頼判定により保守的な fallback 応答へ切り替えたか
	FallbackApplied bool `json:"fallbackApplied"`

	// GroundednessScore 取得根拠にどれだけ沿っているかを 0.0 から 1.0 で表した近似スコア
	GroundednessScore float64 `json:"groundednessScore"`

	// Reason groundedness 判定の簡単な理由
	Reason string                       `json:"reason"`
	Status GroundednessEvaluationStatus `json:"status"`
}

// GroundednessEvaluationStatus defines model for GroundednessEvaluation.Status.
type GroundednessEvaluationStatus string

// KnowledgeDocumentCreateRequest defines model for KnowledgeDocumentCreateRequest.
type KnowledgeDocumentCreateRequest struct {
	AccessScope      *KnowledgeDocumentCreateRequestAccessScope `json:"accessScope,omitempty"`
	AceCategory      KnowledgeDocumentCreateRequestAceCategory  `json:"aceCategory"`
	AllowedUsernames *[]string                                  `json:"allowedUsernames,omitempty"`
	Content          string                                     `json:"content"`
	Title            string                                     `json:"title"`
}

// KnowledgeDocumentCreateRequestAccessScope defines model for KnowledgeDocumentCreateRequest.AccessScope.
type KnowledgeDocumentCreateRequestAccessScope string

// KnowledgeDocumentCreateRequestAceCategory defines model for KnowledgeDocumentCreateRequest.AceCategory.
type KnowledgeDocumentCreateRequestAceCategory string

// KnowledgeDocumentListResponse defines model for KnowledgeDocumentListResponse.
type KnowledgeDocumentListResponse struct {
	Items      []KnowledgeDocumentResponse `json:"items"`
	Limit      int                         `json:"limit"`
	Offset     int                         `json:"offset"`
	TotalCount int64                       `json:"totalCount"`
}

// KnowledgeDocumentResponse defines model for KnowledgeDocumentResponse.
type KnowledgeDocumentResponse struct {
	AccessScope      KnowledgeDocumentResponseAccessScope `json:"accessScope"`
	AceCategory      KnowledgeDocumentResponseAceCategory `json:"aceCategory"`
	AllowedUsernames []string                             `json:"allowedUsernames"`
	Content          string                               `json:"content"`
	CreatedAt        time.Time                            `json:"createdAt"`
	Id               int64                                `json:"id"`
	Title            string                               `json:"title"`
	UpdatedAt        time.Time                            `json:"updatedAt"`
}

// KnowledgeDocumentResponseAccessScope defines model for KnowledgeDocumentResponse.AccessScope.
type KnowledgeDocumentResponseAccessScope string

// KnowledgeDocumentResponseAceCategory defines model for KnowledgeDocumentResponse.AceCategory.
type KnowledgeDocumentResponseAceCategory string

// KnowledgeDocumentUpdateRequest defines model for KnowledgeDocumentUpdateRequest.
type KnowledgeDocumentUpdateRequest struct {
	AccessScope      *KnowledgeDocumentUpdateRequestAccessScope `json:"accessScope,omitempty"`
	AceCategory      KnowledgeDocumentUpdateRequestAceCategory  `json:"aceCategory"`
	AllowedUsernames *[]string                                  `json:"allowedUsernames,omitempty"`
	Content          string                                     `json:"content"`
	Title            string                                     `json:"title"`
}

// KnowledgeDocumentUpdateRequestAccessScope defines model for KnowledgeDocumentUpdateRequest.AccessScope.
type KnowledgeDocumentUpdateRequestAccessScope string

// KnowledgeDocumentUpdateRequestAceCategory defines model for KnowledgeDocumentUpdateRequest.AceCategory.
type KnowledgeDocumentUpdateRequestAceCategory string

// KnowledgeReindexJobAcceptedResponse defines model for KnowledgeReindexJobAcceptedResponse.
type KnowledgeReindexJobAcceptedResponse struct {
	AcceptedAt time.Time `json:"acceptedAt"`
	JobId      string    `json:"jobId"`
	Status     string    `json:"status"`
}

// KnowledgeReindexJobListResponse defines model for KnowledgeReindexJobListResponse.
type KnowledgeReindexJobListResponse struct {
	Items      []KnowledgeReindexJobStatusResponse `json:"items"`
	Limit      int                                 `json:"limit"`
	Offset     int                                 `json:"offset"`
	TotalCount int64                               `json:"totalCount"`
}

// KnowledgeReindexJobStatusResponse defines model for KnowledgeReindexJobStatusResponse.
type KnowledgeReindexJobStatusResponse struct {
	AcceptedAt          time.Time                 `json:"acceptedAt"`
	CompletedAt         *time.Time                `json:"completedAt,omitempty"`
	ErrorMessage        *string                   `json:"errorMessage,omitempty"`
	JobId               string                    `json:"jobId"`
	KnowledgeDocumentId *int64                    `json:"knowledgeDocumentId,omitempty"`
	Result              *KnowledgeReindexResponse `json:"result,omitempty"`
	StartedAt           *time.Time                `json:"startedAt,omitempty"`
	Status              string                    `json:"status"`
}

// KnowledgeReindexResponse defines model for KnowledgeReindexResponse.
type KnowledgeReindexResponse struct {
	ChunksProcessed     int64 `json:"chunksProcessed"`
	DocumentsProcessed  int64 `json:"documentsProcessed"`
	EmbeddingsUpdated   int64 `json:"embeddingsUpdated"`
	VectorSearchEnabled bool  `json:"vectorSearchEnabled"`
}

// MemberContext defines model for MemberContext.
type MemberContext struct {
	// Situation メンバーの現在の状況
	Situation string `json:"situation"`

	// TargetGoal 達成したい目標
	TargetGoal string `json:"targetGoal"`
}

// PromptInjectionEvaluationCaseRequest defines model for PromptInjectionEvaluationCaseRequest.
type PromptInjectionEvaluationCaseRequest struct {
	// ExpectedBlocked true の場合は block が期待される
	ExpectedBlocked bool `json:"expectedBlocked"`

	// Input guard に渡す評価対象文字列
	Input string `json:"input"`

	// Label ケース識別用の任意ラベル
	Label *string `json:"label,omitempty"`
}

// PromptInjectionEvaluationCaseResult defines model for PromptInjectionEvaluationCaseResult.
type PromptInjectionEvaluationCaseResult struct {
	// ActualOutcome BLOCK または ALLOW
	ActualOutcome *string `json:"actualOutcome,omitempty"`
	Blocked       bool    `json:"blocked"`

	// DetectionMessage block 時の guard メッセージ
	DetectionMessage *string `json:"detectionMessage"`
	ExpectedBlocked  bool    `json:"expectedBlocked"`

	// ExpectedOutcome BLOCK または ALLOW
	ExpectedOutcome *string `json:"expectedOutcome,omitempty"`
	Input           string  `json:"input"`
	Label           *string `json:"label,omitempty"`
	Matched         bool    `json:"matched"`
}

// PromptInjectionEvaluationRequest defines model for PromptInjectionEvaluationRequest.
type PromptInjectionEvaluationRequest struct {
	Cases []PromptInjectionEvaluationCaseRequest `json:"cases"`
}

// PromptInjectionEvaluationResponse defines model for PromptInjectionEvaluationResponse.
type PromptInjectionEvaluationResponse struct {
	// Accuracy 全ケースで正しく判定できた割合
	Accuracy              float64                               `json:"accuracy"`
	CaseResults           []PromptInjectionEvaluationCaseResult `json:"caseResults"`
	CorrectlyAllowedCases int                                   `json:"correctlyAllowedCases"`
	CorrectlyBlockedCases int                                   `json:"correctlyBlockedCases"`

	// DetectionRate block が期待されるケースを正しく block できた割合
	DetectionRate        float64 `json:"detectionRate"`
	ExpectedAllowedCases int     `json:"expectedAllowedCases"`
	ExpectedBlockedCases int     `json:"expectedBlockedCases"`

	// FalsePositiveRate allow が期待されるケースを誤って block した割合
	FalsePositiveRate float64 `json:"falsePositiveRate"`
	TotalCases        int     `json:"totalCases"`
}

// RetrievalEvaluationCaseRequest defines model for RetrievalEvaluationCaseRequest.
type RetrievalEvaluationCaseRequest struct {
	ExpectedDocumentTitles []string `json:"expectedDocumentTitles"`

	// Label ケース識別用の任意ラベル
	Label *string `json:"label,omitempty"`
	Query string  `json:"query"`
}

// RetrievalEvaluationCaseResult defines model for RetrievalEvaluationCaseResult.
type RetrievalEvaluationCaseResult struct {
	ExpectedDocumentTitles []string `json:"expectedDocumentTitles"`

	// FirstRelevantRank 最初に期待文書が出現した 1-based rank。一致なしの場合は null。
	FirstRelevantRank       *int     `json:"firstRelevantRank"`
	Label                   *string  `json:"label,omitempty"`
	Matched                 bool     `json:"matched"`
	MatchedDocumentTitles   []string `json:"matchedDocumentTitles"`
	PrecisionAtK            float64  `json:"precisionAtK"`
	Query                   string   `json:"query"`
	RecallAtK               float64  `json:"recallAtK"`
	ReciprocalRank          float64  `json:"reciprocalRank"`
	RetrievedCount          int      `json:"retrievedCount"`
	RetrievedDocumentTitles []string `json:"retrievedDocumentTitles"`
}

// RetrievalEvaluationComparisonRequest defines model for RetrievalEvaluationComparisonRequest.
type RetrievalEvaluationComparisonRequest struct {
	Variants []RetrievalEvaluationVariantRequest `json:"variants"`
}

// RetrievalEvaluationComparisonResponse defines model for RetrievalEvaluationComparisonResponse.
type RetrievalEvaluationComparisonResponse struct {
	VariantResults []RetrievalEvaluationVariantResult `json:"variantResults"`
}

// RetrievalEvaluationRequest defines model for RetrievalEvaluationRequest.
type RetrievalEvaluationRequest struct {
	Cases []RetrievalEvaluationCaseRequest `json:"cases"`

	// TopK 評価時に使う retrieval 件数。未指定時は rag.top-k を使う。
	TopK *int `json:"topK,omitempty"`
}

// RetrievalEvaluationResponse defines model for RetrievalEvaluationResponse.
type RetrievalEvaluationResponse struct {
	// AveragePrecisionAtK ケース単位 Precision@K の平均
	AveragePrecisionAtK float64 `json:"averagePrecisionAtK"`

	// AverageRecallAtK ケース単位 Recall@K の平均
	AverageRecallAtK      float64                         `json:"averageRecallAtK"`
	AverageRetrievedCount float64                         `json:"averageRetrievedCount"`
	CaseResults           []RetrievalEvaluationCaseResult `json:"caseResults"`

	// HitRate 期待文書を1件以上取得できたケースの割合
	HitRate      float64 `json:"hitRate"`
	MatchedCases int     `json:"matchedCases"`

	// MeanReciprocalRank 最初に一致した期待文書の順位から計算した MRR
	MeanReciprocalRank float64 `json:"meanReciprocalRank"`
	TopK               int     `json:"topK"`
	TotalCases         int     `json:"totalCases"`
}

// RetrievalEvaluationVariantRequest defines model for RetrievalEvaluationVariantRequest.
type RetrievalEvaluationVariantRequest struct {
	Label string `json:"label"`

	// MinSimilarityScore この比較条件で使う類似度しきい値。未指定時は既定設定を使う。
	MinSimilarityScore *float64 `json:"minSimilarityScore,omitempty"`

	// RerankEnabled この比較条件で rerank を有効化するか。未指定時は既定設定を使う。
	RerankEnabled *bool `json:"rerankEnabled,omitempty"`

	// TopK この比較条件で使う retrieval 件数
	TopK *int `json:"topK,omitempty"`
}

// RetrievalEvaluationVariantResult defines model for RetrievalEvaluationVariantResult.
type RetrievalEvaluationVariantResult struct {
	AveragePrecisionAtK   float64  `json:"averagePrecisionAtK"`
	AverageRecallAtK      float64  `json:"averageRecallAtK"`
	AverageRetrievedCount float64  `json:"averageRetrievedCount"`
	HitRate               float64  `json:"hitRate"`
	Label                 string   `json:"label"`
	MatchedCases          int      `json:"matchedCases"`
	MeanReciprocalRank    float64  `json:"meanReciprocalRank"`
	MinSimilarityScore    *float64 `json:"minSimilarityScore"`
	RerankEnabled         *bool    `json:"rerankEnabled"`
	TopK                  int      `json:"topK"`
	TotalCases            int      `json:"totalCases"`
}

// RetrievedDocument defines model for RetrievedDocument.
type RetrievedDocument struct {
	AceCategory *RetrievedDocumentAceCategory `json:"aceCategory,omitempty"`
	ChunkIndex  int                           `json:"chunkIndex"`

	// DistanceScore pgvector の cosine distance。vector 検索時のみ設定される。
	DistanceScore *float64 `json:"distanceScore,omitempty"`
	Excerpt       string   `json:"excerpt"`
	Id            int64    `json:"id"`

	// SimilarityScore cosine distance から計算した類似度の近似値。vector 検索時のみ設定される。
	SimilarityScore *float64 `json:"similarityScore,omitempty"`
	Title           string   `json:"title"`
}

// RetrievedDocumentAceCategory defines model for RetrievedDocument.AceCategory.
type RetrievedDocumentAceCategory string

// UsageInfo defines model for UsageInfo.
type UsageInfo struct {
	CompletionTokens int     `json:"completionTokens"`
	EstimatedCostJpy float64 `json:"estimatedCostJpy"`
	Model            string  `json:"model"`
	PromptTokens     int     `json:"promptTokens"`
	TotalTokens      int     `json:"totalTokens"`
}

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	// Limit 取得件数の上限
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 取得開始位置
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Model モデル名で絞り込む
	Model *string `form:"model,omitempty" json:"model,omitempty"`

	// From この日時以降の監査ログを取得する
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To この日時以前の監査ログを取得する
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// GetKnowledgeDocumentsParams defines parameters for GetKnowledgeDocuments.
type GetKnowledgeDocumentsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetKnowledgeReindexJobsParams defines parameters for GetKnowledgeReindexJobs.
type GetKnowledgeReindexJobsParams struct {
	Limit               *int                                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset              *int                                 `form:"offset,omitempty" json:"offset,omitempty"`
	Status              *GetKnowledgeReindexJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	KnowledgeDocumentId *int64                               `form:"knowledgeDocumentId,omitempty" json:"knowledgeDocumentId,omitempty"`

	// AcceptedFrom この日時以降に受け付けたジョブを取得する
	AcceptedFrom *time.Time `form:"acceptedFrom,omitempty" json:"acceptedFrom,omitempty"`

	// AcceptedTo この日時以前に受け付けたジョブを取得する
	AcceptedTo *time.Time `form:"acceptedTo,omitempty" json:"acceptedTo,omitempty"`

	// CompletedFrom この日時以降に完了したジョブを取得する
	CompletedFrom *time.Time `form:"completedFrom,omitempty" json:"completedFrom,omitempty"`

	// CompletedTo この日時以前に完了したジョブを取得する
	CompletedTo *time.Time `form:"completedTo,omitempty" json:"completedTo,omitempty"`

	// SortBy ソート対象項目
	SortBy *GetKnowledgeReindexJobsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// SortDirection ソート方向
	SortDirection *GetKnowledgeReindexJobsParamsSortDirection `form:"sortDirection,omitempty" json:"sortDirection,omitempty"`
}

// GetKnowledgeReindexJobsParamsStatus defines parameters for GetKnowledgeReindexJobs.
type GetKnowledgeReindexJobsParamsStatus string

// GetKnowledgeReindexJobsParamsSortBy defines parameters for GetKnowledgeReindexJobs.
type GetKnowledgeReindexJobsParamsSortBy string

// GetKnowledgeReindexJobsParamsSortDirection defines parameters for GetKnowledgeReindexJobs.
type GetKnowledgeReindexJobsParamsSortDirection string

// EvaluateDefaultRetrievalCasesParams defines parameters for EvaluateDefaultRetrievalCases.
type EvaluateDefaultRetrievalCasesParams struct {
	// TopK 評価時に使う retrieval 件数。未指定時は評価ファイルまたは rag.top-k を使う。
	TopK *int `form:"topK,omitempty" json:"topK,omitempty"`
}

// RunAgentTaskJSONRequestBody defines body for RunAgentTask for application/json ContentType.
type RunAgentTaskJSONRequestBody = AgentTaskRequest

// IssueAuthTokenJSONRequestBody defines body for IssueAuthToken for application/json ContentType.
type IssueAuthTokenJSONRequestBody = AuthTokenRequest

// EvaluateGroundednessJSONRequestBody defines body for EvaluateGroundedness for application/json ContentType.
type EvaluateGroundednessJSONRequestBody = GroundednessCaseEvaluationRequest

// CreateKnowledgeDocumentJSONRequestBody defines body for CreateKnowledgeDocument for application/json ContentType.
type CreateKnowledgeDocumentJSONRequestBody = KnowledgeDocumentCreateRequest

// UpdateKnowledgeDocumentJSONRequestBody defines body for UpdateKnowledgeDocument for application/json ContentType.
type UpdateKnowledgeDocumentJSONRequestBody = KnowledgeDocumentUpdateRequest

// GetAdviceJSONRequestBody defines body for GetAdvice for application/json ContentType.
type GetAdviceJSONRequestBody = AdviceRequest

// EvaluatePromptInjectionJSONRequestBody defines body for EvaluatePromptInjection for application/json ContentType.
type EvaluatePromptInjectionJSONRequestBody = PromptInjectionEvaluationRequest

// EvaluateRetrievalJSONRequestBody defines body for EvaluateRetrieval for application/json ContentType.
type EvaluateRetrievalJSONRequestBody = RetrievalEvaluationRequest

// CompareRetrievalEvaluationsJSONRequestBody defines body for CompareRetrievalEvaluations for application/json ContentType.
type CompareRetrievalEvaluationsJSONRequestBody = RetrievalEvaluationComparisonRequest
